"""initial schema

Revision ID: 16389c42c243
Revises: 
Create Date: 2026-05-07 16:23:29.218607
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '16389c42c243'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('mfa_secret', sa.String(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('alpaca_api_key', sa.String(), nullable=True),
    sa.Column('alpaca_secret_key', sa.String(), nullable=True),
    sa.Column('alpaca_paper', sa.Boolean(), nullable=True),
    sa.Column('trade_fee_absolute', sa.Integer(), nullable=True),
    sa.Column('trade_fee_percent', sa.Integer(), nullable=True),
    sa.Column('min_target_yield', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('p256dh', sa.String(), nullable=False),
    sa.Column('auth', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_id'), 'push_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_id'), 'watchlists', ['id'], unique=False)
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_id'), 'alert_rules', ['id'], unique=False)
    op.create_index(op.f('ix_alert_rules_rule_type'), 'alert_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_alert_rules_symbol'), 'alert_rules', ['symbol'], unique=False)
    op.create_index(op.f('ix_alert_rules_user_id'), 'alert_rules', ['user_id'], unique=False)
    op.create_index(op.f('ix_alert_rules_watchlist_id'), 'alert_rules', ['watchlist_id'], unique=False)
    op.create_table('watchlist_alert_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('alert_key', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('priority_label', sa.String(), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_alert_deliveries_alert_key'), 'watchlist_alert_deliveries', ['alert_key'], unique=False)
    op.create_index(op.f('ix_watchlist_alert_deliveries_channel'), 'watchlist_alert_deliveries', ['channel'], unique=False)
    op.create_index(op.f('ix_watchlist_alert_deliveries_id'), 'watchlist_alert_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_alert_deliveries_sent_at'), 'watchlist_alert_deliveries', ['sent_at'], unique=False)
    op.create_index(op.f('ix_watchlist_alert_deliveries_symbol'), 'watchlist_alert_deliveries', ['symbol'], unique=False)
    op.create_index(op.f('ix_watchlist_alert_deliveries_user_id'), 'watchlist_alert_deliveries', ['user_id'], unique=False)
    op.create_index(op.f('ix_watchlist_alert_deliveries_watchlist_id'), 'watchlist_alert_deliveries', ['watchlist_id'], unique=False)
    op.create_table('watchlist_alert_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('toast_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('min_priority', sa.String(), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_alert_settings_id'), 'watchlist_alert_settings', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_alert_settings_user_id'), 'watchlist_alert_settings', ['user_id'], unique=False)
    op.create_index(op.f('ix_watchlist_alert_settings_watchlist_id'), 'watchlist_alert_settings', ['watchlist_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_items_id'), 'watchlist_items', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_watchlist_id'), 'watchlist_items', ['watchlist_id'], unique=False)
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_rule_id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_alert_rule_id'), 'alert_events', ['alert_rule_id'], unique=False)
    op.create_index(op.f('ix_alert_events_event_type'), 'alert_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_alert_events_id'), 'alert_events', ['id'], unique=False)
    op.create_index(op.f('ix_alert_events_severity'), 'alert_events', ['severity'], unique=False)
    op.create_index(op.f('ix_alert_events_status'), 'alert_events', ['status'], unique=False)
    op.create_index(op.f('ix_alert_events_symbol'), 'alert_events', ['symbol'], unique=False)
    op.create_index(op.f('ix_alert_events_triggered_at'), 'alert_events', ['triggered_at'], unique=False)
    op.create_index(op.f('ix_alert_events_user_id'), 'alert_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_alert_events_watchlist_id'), 'alert_events', ['watchlist_id'], unique=False)
    op.create_table('watchlist_item_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_item_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['watchlist_item_id'], ['watchlist_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_item_tags_id'), 'watchlist_item_tags', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_item_tags_watchlist_item_id'), 'watchlist_item_tags', ['watchlist_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_item_tags_watchlist_item_id'), table_name='watchlist_item_tags')
    op.drop_index(op.f('ix_watchlist_item_tags_id'), table_name='watchlist_item_tags')
    op.drop_table('watchlist_item_tags')
    op.drop_index(op.f('ix_alert_events_watchlist_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_user_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_triggered_at'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_symbol'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_status'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_severity'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_event_type'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_alert_rule_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_watchlist_items_watchlist_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_watchlist_alert_settings_watchlist_id'), table_name='watchlist_alert_settings')
    op.drop_index(op.f('ix_watchlist_alert_settings_user_id'), table_name='watchlist_alert_settings')
    op.drop_index(op.f('ix_watchlist_alert_settings_id'), table_name='watchlist_alert_settings')
    op.drop_table('watchlist_alert_settings')
    op.drop_index(op.f('ix_watchlist_alert_deliveries_watchlist_id'), table_name='watchlist_alert_deliveries')
    op.drop_index(op.f('ix_watchlist_alert_deliveries_user_id'), table_name='watchlist_alert_deliveries')
    op.drop_index(op.f('ix_watchlist_alert_deliveries_symbol'), table_name='watchlist_alert_deliveries')
    op.drop_index(op.f('ix_watchlist_alert_deliveries_sent_at'), table_name='watchlist_alert_deliveries')
    op.drop_index(op.f('ix_watchlist_alert_deliveries_id'), table_name='watchlist_alert_deliveries')
    op.drop_index(op.f('ix_watchlist_alert_deliveries_channel'), table_name='watchlist_alert_deliveries')
    op.drop_index(op.f('ix_watchlist_alert_deliveries_alert_key'), table_name='watchlist_alert_deliveries')
    op.drop_table('watchlist_alert_deliveries')
    op.drop_index(op.f('ix_alert_rules_watchlist_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_user_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_symbol'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_rule_type'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
