"""add alert rules and events

Revision ID: d939f2abcdc2
Revises: b97b927c8690
Create Date: 2026-05-07 18:08:30.067565
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd939f2abcdc2'
down_revision: Union[str, None] = 'b97b927c8690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_id'), 'alert_rules', ['id'], unique=False)
    op.create_index(op.f('ix_alert_rules_rule_type'), 'alert_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_alert_rules_symbol'), 'alert_rules', ['symbol'], unique=False)
    op.create_index(op.f('ix_alert_rules_user_id'), 'alert_rules', ['user_id'], unique=False)
    op.create_index(op.f('ix_alert_rules_watchlist_id'), 'alert_rules', ['watchlist_id'], unique=False)
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_rule_id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_alert_rule_id'), 'alert_events', ['alert_rule_id'], unique=False)
    op.create_index(op.f('ix_alert_events_event_type'), 'alert_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_alert_events_id'), 'alert_events', ['id'], unique=False)
    op.create_index(op.f('ix_alert_events_severity'), 'alert_events', ['severity'], unique=False)
    op.create_index(op.f('ix_alert_events_status'), 'alert_events', ['status'], unique=False)
    op.create_index(op.f('ix_alert_events_symbol'), 'alert_events', ['symbol'], unique=False)
    op.create_index(op.f('ix_alert_events_triggered_at'), 'alert_events', ['triggered_at'], unique=False)
    op.create_index(op.f('ix_alert_events_user_id'), 'alert_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_alert_events_watchlist_id'), 'alert_events', ['watchlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_events_watchlist_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_user_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_triggered_at'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_symbol'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_status'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_severity'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_event_type'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_alert_rule_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_alert_rules_watchlist_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_user_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_symbol'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_rule_type'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
